#!/bin/sh
# Load custom keymap
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# Set env vars from .xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

eval "$(dbus-launch --sh-syntax --exit-with-session)"

# Start background services
pulseaudio --start &

# Start i3
exec i3
