#!/bin/bash

echo "Performing setup..."

package_installed() {
	pacman -Q "$1" &>/dev/null
}

install_package() {
	if ! package_installed "$1"; then
		sudo pacman -S --noconfirm "$1" || exit 1
	fi
}

install_rustup() {
	if ! package_installed rustup; then
		sudo pacman -S --noconfirm rustup || exit 1
	fi
	if ! rustup --version &>/dev/null; then
		rustup default stable || exit 1
	fi
}

install_paru() {
	if ! package_installed paru; then
		cd /tmp || exit 1
		git clone https://aur.archlinux.org/paru.git || exit 1
		cd paru || exit 1
		makepkg -si --noconfirm || exit 1
	fi
}

packages=(
	"neovim"
	"ttf-jetbrains-mono"
	"ttf-noto-nerd"
	"fish"
	"i3"
	"i3blocks"
	"kitty"
	"lazygit"
	"picom"
	"rofi"
	"tmux"
	"ripgrep"
	"fd"
	"feh"
	"bottom"
)
install_tpm() {
	if [ ! -e "$HOME/.config/tmux/plugins/tmux" ]; then
		git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
		~/.tmux/plugins/tpm/scripts/install_plugins.sh
	fi
}

install_rustup
install_paru
install_tpm

for package in "${packages[@]}"; do
	install_package "$package"
done

echo "Setup complete."
